// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49f7TVGJ3Fh_pbBnbZ7ZyPQaRuvi6qmE',
    appId: '1:684768060231:web:53d65f7382625e9b8e2262',
    messagingSenderId: '684768060231',
    projectId: 'isentropic-disk-467315-g9',
    authDomain: 'isentropic-disk-467315-g9.firebaseapp.com',
    storageBucket: 'isentropic-disk-467315-g9.firebasestorage.app',
    measurementId: 'G-JX57H6Y0ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFdlYkf7XexXvJQ553xwG_nIBGF29vqmU',
    appId: '1:684768060231:android:259a97a042fd14558e2262',
    messagingSenderId: '684768060231',
    projectId: 'isentropic-disk-467315-g9',
    storageBucket: 'isentropic-disk-467315-g9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYdrNKwonGhbC5YSBTvfS9FQmt51496o',
    appId: '1:684768060231:ios:2d3d256457c0f4f98e2262',
    messagingSenderId: '684768060231',
    projectId: 'isentropic-disk-467315-g9',
    storageBucket: 'isentropic-disk-467315-g9.firebasestorage.app',
    iosBundleId: 'com.example.googlemaps2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYdrNKwonGhbC5YSBTvfS9FQmt51496o',
    appId: '1:684768060231:ios:2d3d256457c0f4f98e2262',
    messagingSenderId: '684768060231',
    projectId: 'isentropic-disk-467315-g9',
    storageBucket: 'isentropic-disk-467315-g9.firebasestorage.app',
    iosBundleId: 'com.example.googlemaps2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB49f7TVGJ3Fh_pbBnbZ7ZyPQaRuvi6qmE',
    appId: '1:684768060231:web:be3eb76e0e93ee3d8e2262',
    messagingSenderId: '684768060231',
    projectId: 'isentropic-disk-467315-g9',
    authDomain: 'isentropic-disk-467315-g9.firebaseapp.com',
    storageBucket: 'isentropic-disk-467315-g9.firebasestorage.app',
    measurementId: 'G-12G0Z3RJMR',
  );
}
